package btools.router;

import java.util.ArrayList;

import org.junit.Assert;
import org.junit.Assume;
import org.junit.Test;

import btools.util.CheapRuler;

/**
 * Round-trip × nogo interaction on the bundled Dreieich fixture (real segment
 * data, generated by the map-creator test — no download). This combination had
 * zero coverage. The safety property under test: when a hard nogo sits on the
 * corridor a loop would otherwise use, the round-trip must either reroute the
 * loop entirely around the nogo or fail with a clean error — it must never throw
 * or return a loop that drives through the nogo.
 */
public class RoundTripNogoIntegrationTest {

  private static final int START_ILON = RoundTripFixture.START_ILON;
  private static final int START_ILAT = RoundTripFixture.START_ILAT;

  /** Hard circular nogo (NaN weight → edges through the circle are blocked). */
  private static OsmNodeNamed hardNogo(int ilon, int ilat, int radiusMeters) {
    OsmNodeNamed n = new OsmNodeNamed();
    n.ilon = ilon;
    n.ilat = ilat;
    n.name = "nogo" + radiusMeters;
    n.radius = radiusMeters;
    n.nogoWeight = Double.NaN; // hard block
    n.isNogo = true;
    return n;
  }

  private static int distance(OsmPathElement node, OsmNodeNamed nogo) {
    return (int) CheapRuler.distance(node.getILon(), node.getILat(), nogo.ilon, nogo.ilat);
  }

  private static boolean anyNodeWithin(OsmTrack track, OsmNodeNamed nogo) {
    for (OsmPathElement n : track.nodes) {
      if (distance(n, nogo) < nogo.radius) return true;
    }
    return false;
  }

  @Test
  public void hardNogoOnLoopCorridorIsReroutedOrFailsCleanly() {
    // 1. Baseline loop with no nogo. Uses the proven fixture config (default
    //    AUTO algorithm, ~6km loop) that RoundTripScenarioTest relies on.
    OsmTrack baseline = RoundTripFixture.engine("trekking", 90, 1000,
      rc -> rc.roundTripLength = 6000).getFoundTrack();
    Assume.assumeNotNull("fixture could not produce a baseline loop", baseline);

    // 2. Place a hard nogo on the loop's far corridor (the node farthest from
    //    the start is unambiguously on the baseline and well clear of the start
    //    waypoint, so it won't be stripped by cleanNogoList).
    OsmPathElement far = baseline.nodes.get(0);
    int farDist = 0;
    for (OsmPathElement n : baseline.nodes) {
      int d = (int) CheapRuler.distance(START_ILON, START_ILAT, n.getILon(), n.getILat());
      if (d > farDist) {
        farDist = d;
        far = n;
      }
    }
    Assume.assumeTrue("baseline loop too small to place a corridor nogo (" + farDist + "m)",
      farDist > 600);

    OsmNodeNamed nogo = hardNogo(far.getILon(), far.getILat(), 300);
    Assert.assertTrue("test setup: the baseline loop must pass through the nogo",
      anyNodeWithin(baseline, nogo));

    // 3. Re-run with the nogo on the corridor (same config as the baseline).
    RoutingEngine re = RoundTripFixture.engine("trekking", 90, 1000, rc -> {
      rc.roundTripLength = 6000;
      rc.nogopoints = new ArrayList<>();
      rc.nogopoints.add(nogo);
    });
    OsmTrack rerouted = re.getFoundTrack();
    String err = re.getErrorMessage();

    if (rerouted == null) {
      // Clean failure is acceptable — but it must be an explicit error, not a
      // silent null.
      Assert.assertNotNull(
        "a null round-trip must carry a clean error message, not fail silently", err);
      return;
    }

    // 4. A produced loop must be structurally valid (closes, no beeline, bounded
    //    reuse) AND must not enter the hard nogo on any node.
    RoundTripFixture.assertValidLoop(rerouted, "nogo-rerouted", 100.0);
    for (OsmPathElement n : rerouted.nodes) {
      int d = distance(n, nogo);
      Assert.assertTrue(
        "rerouted loop must not enter the hard nogo: node " + d + "m from center (radius "
          + (int) nogo.radius + "m)", d >= nogo.radius);
    }
  }
}
